
data-analysis:
	python data_analysis.py -aws_account_id=<> -aws_region=<> -kf_url=<> -kf_user_name=<> -kf_user_pwd=<> -kf_user_namespace=<>

feature-importance:
	python feature_importance.py -aws_account_id=<> -aws_region=<> -kf_url=<> -kf_user_name=<> -kf_user_pwd=<> -kf_user_namespace=<>

modeling:
	python modeling.py -aws_account_id=<> -aws_region=<> -kf_url=<> -kf_user_name=<> -kf_user_pwd=<> -kf_user_namespace=<>

hyperparameter-tuning:
	python hyperparameter_tuning.py -aws_account_id=<> -aws_region=<> -kf_url=<> -kf_user_name=<> -kf_user_pwd=<> -kf_user_namespace=<>

training:
	python training.py -aws_account_id=<> -aws_region=<> -kf_url=<> -kf_user_name=<> -kf_user_pwd=<> -kf_user_namespace=<>
