apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kiali-sigv4
  name: kiali-sigv4
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali-sigv4
  template:
    metadata:
      labels:
        app: kiali-sigv4
      name: kiali-sigv4
    spec:
      serviceAccountName: $(AMP_SIGV4_IAM_ROLE)
      containers:
        - name: aws-kiali-iamproxy
          image: public.ecr.aws/aws-observability/aws-sigv4-proxy:1.7
          args:
            - --name
            - aps
            - --region
            - $(AWS_REGION)
            - --host
            - aps-workspaces.$(AWS_REGION).amazonaws.com
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kiali-sigv4
  namespace: istio-system
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: kiali-sigv4