
add-profile:
	python kubeflow_user_management.py -user_email=<> -user_name=<> -aws_account_id=<> -aws_region=<> -cluster_name=kubeflow -iam_role_name=kubeflow-user-role -meth=add_profile

delete-profile:
	python kubeflow_user_management.py -user_email=<> -user_name=<> -aws_account_id=<> -aws_region=<> -cluster_name=kubeflow -iam_role_name=kubeflow-user-role -meth=delete_profile
