apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "occupancy"
  namespace: "production"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "s3://shopware-ml-ops-model-store-dev/xgb_model.p"