apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ai-platform
  region: eu-central-1
  version: "1.14"
nodeGroups:
  - desiredCapacity: 2
    instanceType: m5.xlarge
    maxSize: 3
    minSize: 0
    name: cpu-nodegroup
    volumeSize: 30
