apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "$(MODEL_ENDPOINT_NAME)"
  namespace: "$(KF_NAMESPACE)"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    serviceAccountName: inference
    containers:
      #- name: kserve-container
      - image: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_VERSION)
        command:
          - "python"
          - "rest_api.py"
        args:
          - "-model_name"
          - "occupancy-xgb-replicated"
          - "-n_replicas"
          - "2"
        resources:
          requests:
            memory: "512Mi"
            cpu: "2"
          limits:
            memory: "2Gi"
            cpu: "3"