apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "occupancy-xgb"
  namespace: "production"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    serviceAccountName: sa
    containers:
      #- name: kserve-container
      - image: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_VERSION)
        command:
          - "python"
          - "rest_api.py"
        args:
          - "-model_name"
          - "occupancy-xgb"