apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: endpoint-name
  namespace: namespace # profile name
spec:
  predictor:
    model:
      modelFormat:
        name: xgboost
        protocolVersion: "v2"
      storageUri: "s3://your-model-bucket/model.bst"