
enable-katib:
	python kubeflow_katib_management.py -aws_account_id=973450839031 -profile_namespace=production -service_account_name=default-editor -aws_region=eu-central-1 -cluster_name=kubeflow -s3_iam_role_policy_name=AmazonS3FullAccess
