name: Build & Push Kubeflow Pipeline Component Docker Images

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build & push component - analytical data types
        run: |
          export IMAGE_NAME=ml-ops-analytical-data-types
          export IMAGE_TAG=v1
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID_PRODUCTION.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME
          docker buildx create --use
          docker buildx build --push --tag $AWS_ACCOUNT_ID_PRODUCTION.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG --file ml_ops_templates/kubeflow_pipelines/task_pool/v1/analytical_data_types/task_container/Dockerfile .

      - name: Build & push component - analytical data types
        run: |
          export IMAGE_NAME=ml-ops-analytical-data-types
          export IMAGE_TAG=v1
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID_PRODUCTION.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME
          docker buildx create --use
          docker buildx build --push --tag $AWS_ACCOUNT_ID_PRODUCTION.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG --file ml_ops_templates/kubeflow_pipelines/task_pool/v1/analytical_data_types/task_container/Dockerfile .