name: Install Kubeflow on AWS EKS

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Check out code
      uses: actions/checkout@v2
    
    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        #role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        #role-duration-seconds: 1800
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Install Kubeflow
      run: |
        aws configure set region eu-central-1
        aws configure set access_key ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set secret_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        mkdir -p kubeconfig
        aws s3 cp s3://gfb-ml-ops-tf-infrastructure/eks-kubeflow/kubeconfig_kubeflow-cluster ./kubeconfig/
        brew install kubectl
        brew install ksonnet/tap/ks
        brew install aws-iam-authenticator
        export KUBECONFIG=./kubeconfig/kubeconfig_kubeflow-cluster
        export NAMESPACE=kubeflow
        export KUBEFLOW_VERSION=0.2.2
        export KUBEFLOW_DEPLOY=false
        curl https://raw.githubusercontent.com/kubeflow/kubeflow/v${KUBEFLOW_VERSION}/scripts/deploy.sh | bash
        cd ./kubeflow_ks_app/
        ks env set default --namespace ${NAMESPACE}
        ks param set kubeflow-core reportUsage false
        ks apply default
