name: Kubeflow Component Configuration

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y kubectl
          kubectl version --client

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure Kserve & Knative
        run: |
          cd ml_ops_templates/kubeflow_management/model_endpoint
          python kubeflow_model_endpoint_management.py -s3_endpoint=s3.${{ secrets.AWS_REGION }}.amazonaws.com -profile_namespace=${{ secrets.PROFILE_NAMESPACE }} -top_level_domain_name=net -second_level_domain_name=shopware-kubeflow -subdomain_name=dev -service_account_name=sa -aws_region=${{ secrets.PROFILE_NAMESPACE }} -cluster_name=kubeflow -ecr_iam_role_policy_name=AmazonEC2ContainerRegistryReadOnly -s3_iam_role_policy_name=AmazonS3ReadOnlyAccess -meth=add_domain
          python kubeflow_model_endpoint_management.py -s3_endpoint=s3.${{ secrets.AWS_REGION }}.amazonaws.com -profile_namespace=${{ secrets.PROFILE_NAMESPACE }} -top_level_domain_name=net -second_level_domain_name=shopware-kubeflow -subdomain_name=dev -service_account_name=sa -aws_region=${{ secrets.PROFILE_NAMESPACE }} -cluster_name=kubeflow -ecr_iam_role_policy_name=AmazonEC2ContainerRegistryReadOnly -s3_iam_role_policy_name=AmazonS3ReadOnlyAccess -meth=enable_inference_service

      - name: Configure Katib
        run: |
          cd ml_ops_templates/kubeflow_management/katib
          python kubeflow_katib_management.py -aws_account_id=${{ secrets.AWS_ACCOUNT_ID }} -profile_namespace=${{ secrets.PROFILE_NAMESPACE }} -service_account_name=sa -aws_region=${{ secrets.PROFILE_NAMESPACE }} -cluster_name=kubeflow -s3_iam_role_policy_name=AmazonS3FullAccess

      - name: Configure Tensorboard
        run: |
          cd ml_ops_templates/kubeflow_management/tensorboard
          python kubeflow_katib_management.py -aws_account_id=${{ secrets.AWS_ACCOUNT_ID }} -service_account_name=sa -aws_region=${{ secrets.AWS_REGION }} -cluster_name=kubeflow
