name: TEST Install Kubeflow on AWS EKS

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Check out code
      uses: actions/checkout@v3
    
    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        #role-duration-seconds: 1800
        aws-region: eu-central-1

    - name: Install Kubeflow
      run: |
        curl -o aws-iam-authenticator https://amazon-eks.s3.eu-central-1.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/aws-iam-authenticator
        chmod +x aws-iam-authenticator
        sudo mv aws-iam-authenticator /usr/local/bin
        brew install aws-iam-authenticator
        aws configure set region eu-central-1
        aws configure set access_key ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set secret_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        mkdir -p kubeconfig
        aws s3 cp s3://gfb-ml-ops-tf-infrastructure/eks-kubeflow/kubeconfig_kubeflow-cluster ./kubeconfig/
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        export KUBECONFIG=./kubeconfig/kubeconfig_kubeflow-cluster
        export NAMESPACE=kubeflow
        #kubectl create namespace ${NAMESPACE}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 1800
        aws-region: eu-central-1

    - name: Continue installation
      run: |
        wget https://github.com/kubeflow/kfctl/releases/download/v1.2.0/kfctl_v1.2.0-0-gbc038f9_linux.tar.gz
        tar -xvf kfctl_v1.2.0-0-gbc038f9_linux.tar.gz
        export PATH=$PATH:$PWD
        export CONFIG_URI="https://raw.githubusercontent.com/GianniBalistreri/ml-ops-aws-eks-kubeflow/main/ml_ops/kubeflow/kfctl_aws.v1.2.0.yml"
        mkdir kubeflow-cluster && cd kubeflow-cluster
        wget -O kfctl_aws.yaml $CONFIG_URI
        aws eks update-kubeconfig --name kubeflow-cluster
        kfctl apply -V -f kfctl_aws.yaml
        kubectl -n kubeflow get all
        kubectl get ingress -n istio-system
        kubectl patch service -n istio-system istio-ingressgateway -p '{"spec": {"type": "LoadBalancer"}}'  