apiVersion: v1
kind: Secret
metadata:
  name: aws-secret #s3creds
  annotations:
    serving.kserve.io/s3-endpoint: $(S3_ENDPOINT)
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: $(CLUSTER_REGION)
    serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
type: Opaque